baseURL = "https://blog.inhyuck.io/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "Inhyuck's Development Blog :D"
enableRobotsTXT = true
enableEmoji = true
theme = "even"

preserveTaxonomyNames = true
hasCJKLanguage = true     # has chinese/japanese/korean ? # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
paginate = 5                                              # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-119556778-1"      # UA-XXXXXXXX-X
copyright = "inhyuck"            # default: author.name â†“        # é»˜è®¤ä¸ºä¸‹é¢é…ç½®çš„author.name â†“

[author]                  # essential                     # å¿…éœ€
  name = "Inhyuck"

[sitemap]                 # essential                     # å¿…éœ€
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # é…ç½®ç›®å½•
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Post"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  version = "3.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2018"            # Site creation time          # ç«™ç‚¹å»ºç«‹æ—¶é—´

  # site info (optional)                                  # ç«™ç‚¹ä¿¡æ¯ï¼ˆå¯é€‰ï¼Œä¸éœ€è¦çš„å¯ä»¥ç›´æ¥æ³¨é‡Šæ‰ï¼‰
  logoTitle = "ğŸ‘¨â€ğŸ’»"        # default: the title value    # é»˜è®¤å€¼: ä¸Šé¢è®¾ç½®çš„titleå€¼
  keywords = ["Developer"]
  description = "Developer Inhyuck Choi Blog"

  # paginate of archives, tags and categories             # å½’æ¡£ã€æ ‡ç­¾ã€åˆ†ç±»æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®ï¼Œå»ºè®®ä¿®æ”¹ä¸ºä¸€ä¸ªè¾ƒå¤§çš„å€¼
  archivePaginate = 15

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # æ˜¯å¦æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡ä¸é˜…è¯»æ—¶é—´
  moreMeta = false

  # ä¸€äº›å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½ï¼Œåœ¨ archetypes/default.md æŸ¥çœ‹æ›´å¤šä¿¡æ¯ã€‚
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # æ˜¯å¦å¼€å¯ç›®å½•
  autoCollapseToc = false   # Auto expand and collapse toc                              # ç›®å½•è‡ªåŠ¨å±•å¼€/æŠ˜å 
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # æ˜¯å¦å¯ç”¨fancyboxï¼ˆå›¾ç‰‡å¯ç‚¹å‡»ï¼‰
  mathjax = false           # see https://www.mathjax.org/                              # æ˜¯å¦ä½¿ç”¨mathjaxï¼ˆæ•°å­¦å…¬å¼ï¼‰
  mathjaxEnableSingleDollar = false                                                     # æ˜¯å¦ä½¿ç”¨ $...$ å³å¯é€²è¡Œinline latexæ¸²æŸ“
  mathjaxEnableAutoNumber = false                                                       # æ˜¯å¦ä½¿ç”¨å…¬å¼è‡ªåŠ¨ç¼–å·

  postMetaInFooter = true   # contain author, lastMod, markdown link, license           # åŒ…å«ä½œè€…ï¼Œä¸Šæ¬¡ä¿®æ”¹æ—¶é—´ï¼Œmarkdowné“¾æ¥ï¼Œè®¸å¯ä¿¡æ¯
  linkToMarkDown = false    # Only effective when hugo will output .md files.           # é“¾æ¥åˆ°markdownåŸå§‹æ–‡ä»¶ï¼ˆä»…å½“å…è®¸hugoç”Ÿæˆmarkdownæ–‡ä»¶æ—¶æœ‰æ•ˆï¼‰
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key
  livereUID = "MTAyMC8zNjY3MC8xMzIwNQ=="            # LiveRe UID                  # æ¥å¿…åŠ›
  baidu_push = false        # baidu push                  # ç™¾åº¦
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # è°·æ­Œ

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  [params.publicCDN]        # load these files from public cdn                          # å¯ç”¨å…¬å…±CDNï¼Œéœ€è‡ªè¡Œå®šä¹‰
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    gitalkJS = '<script src="https://cdn.jsdelivr.net/npm/gitalk@1.2.2/dist/gitalk.min.js" integrity="sha256-DcjhdbufsHMHflFjZtKNFnPKOAL2ybOxGcPOR4MtnJg=" crossorigin="anonymous"></script>'
    gitalkCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1.2.2/dist/gitalk.css" integrity="sha256-rJVe5uyYRXdLM+Kkoj7JtN+9qI0bZTxkYTaNWODpg7U=" crossorigin="anonymous">'

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
    enable = false
    options = ""

  [params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
    enable = false
    options = ""            # default: "{theme: 'simple'}"

  [params.busuanzi]         # count web traffic by busuanzi                             # æ˜¯å¦ä½¿ç”¨ä¸è’œå­ç»Ÿè®¡ç«™ç‚¹è®¿é—®é‡
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]                                         # æ–‡ç« æ‰“èµ
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # å¾®ä¿¡äºŒç»´ç 
    alipay = "/path/to/your/alipay-qr-code.png"           # æ”¯ä»˜å®äºŒç»´ç 

  [params.social]                                         # ç¤¾äº¤é“¾æ¥
    a-email = "mailto:dlsgur1447@gmail.com"
    # b-stack-overflow = "http://localhost:1313"
    # c-twitter = "http://localhost:1313"
    d-facebook = "https://www.facebook.com/inhyuck.choi.549"
    # e-linkedin = "http://localhost:1313"
    f-google = "https://plus.google.com/106407520199025600618"
    g-github = "https://github.com/inhyuck"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    k-pocket = "https://getpocket.com/@326pfTM8AfuqMdf862g2ePUg6cddA618by9S74W85eN465jf530ZbQuQg18aQ849"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"

# å°†ä¸‹é¢è¿™æ®µé…ç½®å–æ¶ˆæ³¨é‡Šå¯ä»¥ä½¿ hugo ç”Ÿæˆ .md æ–‡ä»¶
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
